spring:
  application:
    name: demo-dubbo-server-a
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.2:8849,192.168.31.2:8848,192.168.31.2:8847
dubbo:
  scan:
    base-packages: com.seryts.c2c.servera
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: spring-cloud://192.168.31.2
server:
  port: 8081